[package]
name = "DatingSimulation"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.8"
rand = "0.8.5"
uuid = { version = "1.10.0", features = ["fast-rng", "macro-diagnostics", "v4"] }
